import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ImgCard from '../comps/ImgCard';
import NavBar from '../comps/Navbar/v2';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ImgCard 
      bg="#FDE8CA"
      >
        <h3>This is a children in the tag</h3>
        More Stuff
        <hr />
        Yay
      </ImgCard>
      <ImgCard 
        tcl="#ABC980"
        img="https://placekitten.com/300/300" />

      <NavBar />


      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My App!</a>
        </h1>

        <p className={styles.description}>
          Hi{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>
    </div>
  )
}
